### ISSUE TITLE
Theme art update: RetroArch to System

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#101]
Currently it themes have an ES entry called RetroArch, but it has since expanded to include several system functions. Can we update the art to reflect this? @tlayne

**Comment by tlayne** [comment]
Yes this is just the image that is mapped to system scripts. My image just says Retro. If you want to change the config theme name to something else let me know and I can change the file name on my side.

**Comment by tlayne** [comment]
Even better if someone could get me a white png with clear background that says RetroRoller I could use that.

**Comment by npaladin2000** [comment]
I just want to change the image, maybe one of the ones that new guy in the channel posted a few days ago might work? THey had a black background so that would be easy enough to convert to transparent.

**Comment by tlayne** [comment]
Sure! Send it my way.

**Comment by npaladin2000** [comment]
Actually I found your white png too

![logo](https://user-images.githubusercontent.com/43549566/83983173-2c7e8180-a8fa-11ea-82b5-493004a8555c.png)
![Untitled-1](https://user-images.githubusercontent.com/43549566/83983175-31433580-a8fa-11ea-9865-c105cfa81226.png)

**Comment by npaladin2000** [comment]
Oh what's m00dy's id on here? We should tag him too

**Comment by tlayne** [comment]
@M00DY-DEV

**Comment by s4ilence** [comment]
![rr](https://user-images.githubusercontent.com/60616144/84025317-63a56f00-a99c-11ea-86e2-c9688d48ddfa.png)


here is the png for that image transparent background.. if you want to use it

**Comment by npaladin2000** [comment]
While I do like the new one, I'm thinking we should probably be consistent and use the current one. I'll leave the new one up there in case anyone wants to build a new theme around it though.

**Comment by tlayne** [comment]
Since my theme isn’t the default I feel like it would be okay for me to use the unofficial one. What do you guys think?

**Comment by npaladin2000** [comment]
I like both logos. But since we're offering both as installable packages, they're both to some degree "official" and I guess should use the official art.  But that's my opinion, I'll leave it up to you guys and @valadaa48

**Comment by M00DY-DEV** [comment]
Hey @tlayne is this what you're using?

https://raw.githubusercontent.com/tlayne/es-theme-minimal/master/Minimal/art/png/retroarch.png

**Comment by M00DY-DEV** [comment]
@tlayne also, do you want to change your config to point to a new file or do you still want to use retroarch.png? I recommend rr.png or retroroller.png.

What do you guys think of this to replace Retroarch, it's sized to the image you're using for your Minimal theme:


![retroarch](https://user-images.githubusercontent.com/61675748/84063268-cee84480-a98e-11ea-95b6-01dd201b1009.png)

**Comment by npaladin2000** [comment]
I like it.  Everyone, to see it make sure you click on that blank looking white space :)

**Comment by tlayne** [comment]
Downloaded it. @npaladin2000 you are the one that manages the config so let us know if you want to change the config name under theme and we will match our PNG's accordingly.

**Comment by npaladin2000** [comment]
Let's just use the same PNG and theme names and replace the art. Fewer changes that way, and less chances for me to make a typo :)

**Comment by tlayne** [comment]
sounds good you can close if M00D is ready.

**Comment by npaladin2000** [comment]
@M00DY-DEV let us know when you're set and I'll close this out.

**Comment by M00DY-DEV** [comment]
I just updated the theme with these images. If you guys are good with then feel free to close it out.

![SLBG](https://user-images.githubusercontent.com/61675748/84071097-27bdda00-a99b-11ea-8172-1eb1ce41b563.jpg)
![GMBG](https://user-images.githubusercontent.com/61675748/84071100-28567080-a99b-11ea-94b1-b22600920b3b.jpg)

**Comment by npaladin2000** [comment]
Oh wow, that is VERY sharp.
