### ISSUE TITLE
es-theme-minimal package for RC

### ISSUE THREAD

**Issue by tlayne** [valadaa48/retroroller#105]
Applied all of @npaladin2000 's suggestions. Can someone Package this for me on https://github.com/tlayne/es-theme-minimal/commit/c381a4d123e9e0f515453a7e927a5f2b03d97981

I'll stop being lazy soon, I promise. 😄

**Comment by valadaa48** [comment]
Is this the final update?

**Comment by tlayne** [comment]
It's final for the release candidate build. If any other updates are required in the future I will make the package myself.

**Comment by valadaa48** [comment]
thanks, pushed
