### ISSUE TITLE
Auto-Save/Load + RetroAchievements: Game freezes on exit

### ISSUE THREAD

**Issue by adventureFAN** [valadaa48/retroroller#108]
I think I found a issue with the combination of "Auto Load/Save" and "RetroAchievements". When you turn both options On some games freeze when you exit the game.

This occurs with RetroLauncher (RetroArch) and EmuELEC ES.

**Comment by npaladin2000** [comment]
I can confirm this on both SNES and GBA.

**Comment by npaladin2000** [comment]
Confirmed rolling back RetroArch does NOT fix the issue

**Comment by npaladin2000** [comment]
This appears to be an upstream issue?

**Comment by valadaa48** [comment]
Related https://github.com/libretro/RetroArch/issues/10943

**Comment by valadaa48** [comment]
Released retroarch-odroidgo2 1.8.9-10 with this fix
