### ISSUE TITLE
RetroArch cores missing from image

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#110]
The following probably need to be included in the image at the start:

Picodrive (Sega 32x, this is a 32 bit core unfortunately, the rest of the Sega products use 64 bit cores but this doesn't work there)
mGBA (GBA, SuperGB)

**Comment by valadaa48** [comment]
It's a lot of work creating images and I can't keep doing this indefinitely. I think there needs to be clear post-install documentation on how to online update packages + cores.

**Comment by npaladin2000** [comment]
I agree, but if we're going to have a core preconfigured for use it should probably already be present in the image rather than having to retrieve it. Probably just note this down for the next image you make, should be no need to re do the image just for this.

**Comment by valadaa48** [comment]
Is it only picodrive that is missing?

**Comment by mikepurvis** [comment]
I would even support going the other direction, and trimming it right down to the bare-bones. I ended up uninstalling the cores that shipped on the RRVL image in favour of ones installed using the online updater, as none of the ones it came with actually worked for me.
