### ISSUE TITLE
RetroArch switch 32x to 64 bit PicoDrive core

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#111]
Attempt to compile picodrive core as 64 bit to reduce 32 bit dependencies

**Comment by asoderq** [comment]
I just built this commit without problem: https://github.com/irixxxx/picodrive/commit/62c7479bb154d1a6ce824054ea80fbf245785810

**Comment by valadaa48** [comment]
@sydarn2 built a 64bit version. It's downloadable from the retroarch updater.
