### ISSUE TITLE
Can't exit dreamcast emulator when launched from ES

### ISSUE THREAD

**Issue by christianhaitian** [valadaa48/retroroller#113]
Issue occurs with powerstone 1 and Marvel vs Capcom 2 cdi images.  Games run but when you press F1 key, game just halts and system crashes.  Power button has to be held for 10+ seconds to force shutdown the system.

**Comment by M00DY-DEV** [comment]
Hey @christianhaitian , this is a known issue. I believe it's an issue with saving on exit.

**Comment by christianhaitian** [comment]
Good to know.  If there is another issue recorded on this, feel free to close this issue.
