### ISSUE TITLE
EmuElec - ability to modify Advanced Game Options in ES

### ISSUE THREAD

**Issue by M00DY-DEV** [valadaa48/retroroller#116]
This is handy if you want to change ROM specific options such as core. MAME ROMs can use this feature.

**Comment by npaladin2000** [comment]
We might implement core selection but other than that we need to disable this menu in ES. @valadaa48 I got a question on Reddit about that too, can we disable that menu for now?

**Comment by valadaa48** [comment]
Disabled the menu in emuelec-emulationstation-3530

**Comment by npaladin2000** [comment]
@valadaa48 looks like the wrong menu got disabled. I still see this one, but the screensaver options seem to be gone.

**Comment by valadaa48** [comment]
Closing this in favor of RRVL's ES
