### ISSUE TITLE
ppsspp-odroid2 package testing

### ISSUE THREAD

**Issue by valadaa48** [valadaa48/retroroller#117]
Built from latest upstream instead of Crash's repo. Performance seems good. The menu controls are all messed up if someone wants to take a look. There is a gamecontrollerdb.txt with odroidgo2 mappings but I don't think it seems to help.

**Comment by NeonLightning** [comment]
FMV patch that made a difference in my personal tests of compiling. i'll update this if it's still needed or not. https://github.com/EmuELEC/EmuELEC/blob/master/packages/sx05re/emulators/PPSSPPSDL/patches/PPSSPPSDL-05-fix-fmv-stutter.patch

**Comment by valadaa48** [comment]
v11 mapping and FMV fixes applied to ppsspp-odroidgo2 on RRVL
