### ISSUE TITLE
Using spring launcher to launch Retroarch 32 from Retroarch 64 doesn't return to 64 when quitting (unless it's your default launcher)

### ISSUE THREAD

**Issue by Cwiiis** [valadaa48/retroroller#121]
If you have RetroLauncher as your default launcher and you happen to launch a game that uses Retroarch 32 via the spring loader core from Retroarch 64, closing content has you remain in Retroarch 32 and quitting takes you back to RetroLauncher rather than Retroarch 64. It'd be good if quitting took you back to Retroarch 64 (and same with closing content, though I suspect that'd be harder).

**Comment by valadaa48** [comment]
This probably won't be doable without custom compilig retroarch32 to relaunch retroarch32 (I think it's hardcoded to launch retroarch which is 64bit). I think it's a minor annoyance tbh.
