### ISSUE TITLE
Hot Key functionality broken after doing System Update

### ISSUE THREAD

**Issue by chrismillr** [valadaa48/retroroller#123]
Using F3 + Up/Down, Left/Right, and R/L to set brightness, volume, and governors seems to no longer work after performing a system update this morning.

**Comment by npaladin2000** [comment]
It was switched, F2 I think.

**Comment by chrismillr** [comment]
Thanks. That fixed the issue. Neither works on the main boot application though. The hotkey is still listed as F3, while F2 launches RA32.

**Comment by npaladin2000** [comment]
@valadaa48 I assume this is going to require a config change to retrolauncher.toml?

**Comment by valadaa48** [comment]
yes it will

**Comment by valadaa48** [comment]
configs are updated

**Comment by chrismillr** [comment]
![IMG_20200619_094323](https://user-images.githubusercontent.com/5478392/85159113-e981af80-b211-11ea-8bbc-c559e57e6226.jpg)
Its still not showing properly on RetroLauncher after performing a System Update.

**Comment by nvllsvm** [comment]
@chrismillr I had to manually update ~/.config/retrolauncher/retrolauncher.toml after the update.

**Comment by valadaa48** [comment]
system update doesn't change user configs and until we have a config-synchronization mechanism all config related changes need to be merged/copied manually from the configs dir @npaladin2000 .
