### ISSUE TITLE
dosbox-staging from pacman not working

### ISSUE THREAD

**Issue by suetlung** [valadaa48/retroroller#126]
libretro dosbox core is too slow.
I am trying to install dosbox-staging from pacman and get it run.

It started but nothing showed up. Do I need to set anything in the conf?

**Comment by valadaa48** [comment]
Someone here got it working and has a config. If they didn't post it to the wiki then perhaps you can ask around in the RetroGame Handhelds discord.

**Comment by valadaa48** [comment]
pcgamer on discord is the person I think who got it working, not sure if he posted his config

**Comment by suetlung** [comment]
Sorry I am not so familiar with Discord. I joined https://discord.gg/p4uRmCd but cannot see OGA channel. Do I need to do something to see it? Sorry for stupid questions.

**Comment by valadaa48** [comment]
Closing this in favor of dosbox-staging in RRVL.
