### ISSUE TITLE
[Feature Request] Include Devilutionx

### ISSUE THREAD

**Issue by NeonLightning** [valadaa48/retroroller#127]
adding diablo to the roster would be nice.
i'd suggest going with stable.
https://github.com/diasurgical/devilutionX/archive/1.0.1.tar.gz
that way you can also use these patches but they are personal preference i suppose.
https://github.com/Manuel-K/devilutionX-QOL-patches

**Comment by valadaa48** [comment]
@NeonLightning `sudo xbps-install devilutionX` in RRVL will install it. Let me know if it works for you.

**Comment by tlayne** [comment]
Package is available for anyone who wishes to download. No longer an issue.
