### ISSUE TITLE
[Feature Request] RVGL

### ISSUE THREAD

**Issue by NeonLightning** [valadaa48/retroroller#128]
If possible it would be good to get rvgl most of the code and assets are open source but the core itself isn't yet. so it might be difficult
though there is an odroid binary for both 64 and 32 bit already but they are for specific distros.

here are my personal notes right now on getting it running right now on retroroller and emuelec
https://pastebin.com/cTskspSW

**Comment by valadaa48** [comment]
We can package this as an opk
