### ISSUE TITLE
RA menu background doesn't disappear after resume to the game when using oga driver.

### ISSUE THREAD

**Issue by NOirBRight** [valadaa48/retroroller#139]
I set the menu scale to the full screen (3:2), but it will not disappear after resume to 4:3 games.
![image](https://user-images.githubusercontent.com/271412/86150587-2f067c80-bb30-11ea-8039-4ac9afad4c9b.png)
![image](https://user-images.githubusercontent.com/271412/86150614-34fc5d80-bb30-11ea-8ca4-c4ce1d2e565e.png)

**Comment by valadaa48** [comment]
Closing as this belongs on the Retroarch github.
