### ISSUE TITLE
possibly set game controller db by default

### ISSUE THREAD

**Issue by NeonLightning** [valadaa48/retroroller#140]
could you add add a global env variable for
SDL_GAMECONTROLLERCONFIG
and
SDL_GAMECONTROLLERCONFIG_FILE
the first one will depend on v1.0 or v1.1 though so i'm not sure how to implement it.

**Comment by valadaa48** [comment]
Can you give a working example that's tested? I mentioned in chat how to check if you're on v10 or v11.

**Comment by valadaa48** [comment]
This has been patched in the SDL2 libs directly in RRVL.
