### ISSUE TITLE
Make a Ports Spring core

### ISSUE THREAD

**Issue by NeonLightning** [valadaa48/retroroller#141]
title says it all. if someone wants to make a spring for running sh scripts and pr it that'd be great.

**Comment by valadaa48** [comment]
Actually I don't really understand this. Can you explain what this means?

**Comment by NeonLightning** [comment]
oh as was said on discord. me and noir were thinking there could be a spring to load any sh instead of making springs for each port. and just have users have a folder of port scripts themselves. it'll allow for more than just ports potentially.

**Comment by valadaa48** [comment]
Can you provide examples? Right now you can make a spring_sh that loads any sh script you browse. I guess I don't really understand the ask here.

**Comment by NeonLightning** [comment]
that's what i'm saying. is just including one for the enduser preinstalled would be good.

**Comment by valadaa48** [comment]
I made a spring_shell in rr-base 1.1.1, test that out with your .sh to launch your port

**Comment by NeonLightning** [comment]
i mentioned it on discord but it worked
