### ISSUE TITLE
ParaLLEl core broken (Void)

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#143]
ParaLLEl core (Nintendo 64 emulator) doesn't launch in Void Retroarch.

**Comment by vivlim** [comment]
ParaLLEl is looking for `libGLESv2.so` but can't find it in `/usr/lib`.

This worked for me:
```
cd /usr/lib && ln -s libGLESv2.so.2 libGLESv2.so
```

**Comment by shoesio** [comment]
This doesn't seem to work for me - are you using RRVL or Retroroller Arch (standard)?

**Comment by valadaa48** [comment]
I can't reproduce this. ParaLLEl worked out of the box for me on latest RRVL. We can reopen if others see this issue.
