### ISSUE TITLE
Request from Reddit to port EasyRPG (Ports)

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#151]

**Comment by npaladin2000** [comment]
https://github.com/EasyRPG

**Comment by npaladin2000** [comment]
I suppose we could also port the EasyRPG RetroArch core.

**Comment by Safarikniv** [comment]
Retroarch core for EasyRPG is already in the repo.

**Comment by npaladin2000** [comment]
Closing, the core is good enough.
