### ISSUE TITLE
RRVL: wifi does not work for Edimax Wifi Dongle

### ISSUE THREAD

**Issue by klundry** [valadaa48/retroroller#152]
I'm using an original Go Advance with an edimax wifi dongle which works fine with arch based retroroller but does not work with RRVL. I have edited the wpa_supplicant.conf with my credentials.

**Comment by Safarikniv** [comment]
Have you edited wpa_supplicant.conf on the the boot partition, or directly in /etc?

Boot partition is the correct place.

**Comment by klundry** [comment]
I edited the file on the boot partition.

**Comment by valadaa48** [comment]
Do you know what kernel you were using in RR? was it the specialized rr kernel in testing or was it the default one?

**Comment by klundry** [comment]
The default. I didn't compile a new kernel or install a different one.

**Comment by valadaa48** [comment]
It could be related to wpa_supplicant or it could be related to the driver not being in the kernel. Are you able to try the -rr kernel in RR to see if your device is recognized? I think you need to enable the testing-repo for that. If it works, then I suspect it's wpa_supplicant.

**Comment by valadaa48** [comment]
kernel -3 adds a boat load of wifi drivers. Can you provide the lusb output of your edimax?

**Comment by klundry** [comment]
I get command not found when I try to run lsusb but dmesg gives me this. I'm not sure if that's helpful or not. 

[    6.851335] usbcore: registered new interface driver rtl8192cu

**Comment by klundry** [comment]
Wifi is working now after updating via usb ethernet adapter.

**Comment by valadaa48** [comment]
RRVL final image will be released so hopefully this won't be an issue.
