### ISSUE TITLE
RRVL: Add Reboot and Shutdown options to RetroArch [Feature Request]

### ISSUE THREAD

**Issue by klundry** [valadaa48/retroroller#153]
There are no options to cleanly shutdown or reboot the system.

**Comment by klundry** [comment]
I just saw that there is a key combo to shutdown. It would be nice to have a menu item for this as well and also a reboot option.

**Comment by valadaa48** [comment]
We'll look into adding this to RetroArch. It's currently available in the ES package as well if that's your jam.

**Comment by valadaa48** [comment]
This was added to the latest retroarch in RRVL
