### ISSUE TITLE
RRVL: Updates overwrite logo.bmp

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#157]
Updates keep overwriting my custom logo.bmp file. And we should have a separate logo.bmp for RRVL.

**Comment by shoesio** [comment]
Can we have a way to keep a custom boot logo after updates? I’m thinking maybe a custom file name that gets copied over the stock logo after an update, or just not replacing the boot logo on update.

**Comment by valadaa48** [comment]
Fixed in `rr-base-1.2.0_1`

**Comment by npaladin2000** [comment]
New logo added in  void linux PR
