### ISSUE TITLE
RRVL - Sudo update as a spring please

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#159]
Can we have an option in Retroarch to update the system please? Either a command in the main menu, or via a spring.

**Comment by valadaa48** [comment]
We can do this as spring to shell

**Comment by shoesio** [comment]
What would happen without correct time sync? I seem to need to manually set the time before every update now

**Comment by valadaa48** [comment]
Did you enable chrony yet?

**Comment by valadaa48** [comment]
This will be in the next release of RRVL.
