### ISSUE TITLE
Rrvl Automatic update option

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#160]
Can we have an option to automatically update, preferably a few days behind bleeding edge in case of emergency rollbacks :)

**Comment by valadaa48** [comment]
RRVL is bleeding edge! I don't think I'll be making a testing repo for it, users will have to know how to downgrade or wait for the fix. Also, I'm against autoupdates, problems during update will only confuse matters and people will start complaining that the OS is broken without even knowing why.
