### ISSUE TITLE
TIC-80 core for RR and RRVL

### ISSUE THREAD

**Issue by klundry** [valadaa48/retroroller#164]
I was able to compile the TIC-80 core easily on RetroRoller but I am getting an error with cmake on RRVL. Can we get the core added to the repo?

**Comment by valadaa48** [comment]
@npaladin2000 or safarikniv on discord should be able to help get this core added to the repo. Alternatively you can copy it over manually. Thanks for compiling it.

**Comment by klundry** [comment]
Yes, I've copied it to .config/retroarch/cores and its working.

**Comment by ofuangka** [comment]
@klundry Can you can share the compiled core so it can be added to the repo? I'd been having issues compiling it myself.

**Comment by klundry** [comment]
Sure. How would you like me to share it with you?

**Comment by valadaa48** [comment]
Is it possible to post a link to it? We can add it to the retroarch core repo.

**Comment by klundry** [comment]
@valadaa48 Forgot you can upload file to github directly in the issues.
[tic80_libretro.zip](https://github.com/valadaa48/retroroller/files/5151564/tic80_libretro.zip)

**Comment by valadaa48** [comment]
@klundry I added this core from my own optimized build to the core downloader
