### ISSUE TITLE
How to switch from retroarch to retrolauncher on RRVL?

### ISSUE THREAD

**Issue by klundry** [valadaa48/retroroller#165]
I have installed retrolauncher on RRVL and I'm assuming I can disable retroarch launching by default by doing removing the symlink in /var/service but I don't see a retrolauncher service in /etc/sv.

**Comment by valadaa48** [comment]
I think for now until it's fixed in the package you can try to create a service: you should be able to copy retroarch from /etc/sv to retroaluncher and edit the command in the file in that directory and try it out. If you get it working please post back here and that will help with integration.

**Comment by valadaa48** [comment]
@klundry FYI, this is being worked on!

**Comment by klundry** [comment]
Awesome, thanks!

**Comment by valadaa48** [comment]
There is a RetroLauncher available in RRVL now. Not sure if you want to use it as I think RetroArch is just as powerful with Spring launchers. I'll close this for now.

**Comment by klundry** [comment]
It is available but does not work unfortunately. It just boots to a blinking cursor. I personally would like to have it but realize I'm probably in the extreme minority :).
