### ISSUE TITLE
PC-FX roms launching from retrolauncher

### ISSUE THREAD

**Issue by mariovirgili** [valadaa48/retroroller#169]
In order to launch pc-fx games, I suggest to add the following lines to the retrolauncher.toml config:

[[context_menu]]
name = "pcfx"
cmd = "performance on; retroarch -L ~/.config/retroarch/cores/mednafen_pcfx_libretro.so {path}; performance off"
path = "/roms/pcfx"
term = true

**Comment by valadaa48** [comment]
Thanks for the note and I'm sure it will be useful for RR users.
