### ISSUE TITLE
Using 5.8 Kernel

### ISSUE THREAD

**Issue by ouroboros420** [valadaa48/retroroller#173]
I've read that the Linux 5.8 Kernel has official support for the OGA. We might want to use that, it might give us better results.

**Comment by valadaa48** [comment]
I was experimenting with it awhile ago but I think it's still missing a few kernel drivers such as rga2 for hw scaling and rotation. Hopefully the few remaining pieces can be ported and we'll surely use it.

**Comment by valadaa48** [comment]
Closing this for now, but know that I'm keeping a close eye on 4.19 and 5.9 development to be offered.
