### ISSUE TITLE
Trying to launch games while killing retrolauncher. Any help?

### ISSUE THREAD

**Issue by mariovirgili** [valadaa48/retroroller#175]
Because of 5% of CPU time wasted by retrolauncher, I was thinking about launching games using retrolauncher's browser and simultaneously kill retrolauncher to free resources.

I ended up with a cmd sequence that builds and execute a bash script like this:

#!/bin/bash
performance on
systemctl stop retrolauncher.service
retroarch -L ~/.config/retroarch/cores/fbneo_libretro.so /roms/arcade/aoh.zip >/dev/null 2>&1
performance off
systemctl restart retrolauncher.service
 
the problem is that retrolaucher.py call the bash -c command, the child process then call the script, but when the script stops retrolauncher.service, the retrolauncher process kills the bash command that kills the script.

Result: after killing retrolauncher.service the whole process stops and I have to manually restart retrolauncher.

Is it possibile to spawn a whole new process and not a child process while processing the bash -c command in python?
Using Popen in retrolauncher.py would help?

Before asking I tried all the nohup, &, &!, disown combination in the cmd block with no success.

I hereby attach the modified config (added .txt for uploading)
[retrolauncher.toml.txt](https://github.com/valadaa48/retroroller/files/5112611/retrolauncher.toml.txt)

**Comment by valadaa48** [comment]
RRVL launches into RA directly, perhaps that would be a reasonable workflow?

**Comment by mariovirgili** [comment]
Yeah, it could be, but RR is easier to use and configure than RRVL. I’m thinking about the average user, with little experience in using Linux, bash, permissions, etc.
And it’s a personal challenge for me yet! :)

**Comment by valadaa48** [comment]
Hmm, I would think RRVL is basically identical to RR in terms of operational management. Do you have specific examples to share? I'm asking because my focus is on RRVL and I'm curious what's missing compared to RR.

**Comment by mariovirgili** [comment]
well, I'm a former batocera user, passed to RR, which is my main OS used with a 256Gb card.
I installed in a 32Gb card RRVL yesterday, just to wipe it away after an hour in favour of Emuelec Test. I found that after some troubles during installation, including a kernel panic, the system runs well, but not all the roms are working out of the box. I mean, I copied the bios dir from RR to RRVL, placed it into the retroarch path (so the path would be .config/retroarch/bios if I'm not wrong remembering) and tried gameboy, pcfx, n64 and dreamcast roms.
Obviously I unpacked them, so no .7z/.rar or .zip files existed. But only gameboy worked at first run, n64, dc and pcfx were not working and I cannot know why! That's because when retroarch encounters errors, it returns to the main menu promptly. So I cannot find any error. I tried to run retroarch from ssh, just to read the log and eventually find the errors, with no success.
The roms were all 755, the .cue files corrected, they worked flawlessly on RR.
So, without any desire to spend more time on discovering why things were not working, I totally dd-it away and installed other OS.
In RR instead, I can customize all and launch roms via retrolauncher, see the output, read the logs, it's much easier.
The only advantage in using RRVL would be the 5% saved by not using retrolauncher, but I will find a way to save it in RR also.
Thanks for your great work on both systems though.

**Comment by valadaa48** [comment]
Thanks for this writeup. Indeed debugging is a challenge on these systems and I see how RL is helpful in this regard. I'm not sure about the issues you experienced launching roms - do you know if you downloaded the core info files and cores from the retroarch updater? RRVL doesn't include anything out of the box.

I'll think some more on the other feedback.

**Comment by mariovirgili** [comment]
yes, I downloaded only the cores needed for the roms installed. Mgba, Mupen64, flycast and beetlebox for pcfx.

If you want, I can give it another try, but I need to know how to read the retroarch error log file. I tried to 'find / -name retroarch*' to find it without success.

**Comment by mariovirgili** [comment]
another thing: because I needed unzip, I installed it using the 'arm-xbps install' command, but the path were it installs it is not included in the PATH env variable, so I have to call it using the full path which was a complex path like /usr/opt/bin/user/sbin/unzip (just for example). Can you add the installation path to the PATH just to avoid the above?

**Comment by valadaa48** [comment]
the surest way of debugging is to ssh in and run the command from the shell depending on what you're launching:

if it's just retroarch 64bit then something like `retroarch -v -L <path to core> <path to rom>` and if it's mupen64 standalone (that is launched via spring) so check the spring info file in your .config/retroarch/cores/ dir to see the command and paste it replacing the %s with the rom path (you may need to escape the path if there are spaces or surrounding in double quotes).

**Comment by valadaa48** [comment]
> another thing: because I needed unzip, I installed it using the 'arm-xbps install' command, but the path were it installs it is not included in the PATH env variable, so I have to call it using the full path which was a complex path like /usr/opt/bin/user/sbin/unzip (just for example). Can you add the installation path to the PATH just to avoid the above?

arm-xbps install is actually for 32bit which you almost certainly don't want. The only 32bit apps are retroarch 32 and its dependencies. You want to use xbps-install (64bit) for any apps you want.

**Comment by mariovirgili** [comment]
> arm-xbps install is actually for 32bit which you almost certainly don't want. The only 32bit apps are retroarch 32 and its dependencies. You want to use xbps-install (64bit) for any apps you want.
<

Ok, got it. Thanks.
Could you just update the wiki accordingly? I think this is an useful info for all the users interested in.

**Comment by npaladin2000** [comment]
> > arm-xbps install is actually for 32bit which you almost certainly don't want. The only 32bit apps are retroarch 32 and its dependencies. You want to use xbps-install (64bit) for any apps you want.
> > <
> 
> Ok, got it. Thanks.
> Could you just explain it better in the wiki? I think this is an useful info for all the users interested in that are dumbs like me.

Done

**Comment by mariovirgili** [comment]
> the surest way of debugging is to ssh in and run the command from the shell depending on what you're launching:
> 
> if it's just retroarch 64bit then something like `retroarch -v -L <path to core> <path to rom>` and if it's mupen64 standalone (that is launched via spring) so check the spring info file in your .config/retroarch/cores/ dir to see the command and paste it replacing the %s with the rom path (you may need to escape the path if there are spaces or surrounding in double quotes).

Done and fixed it. See
https://github.com/valadaa48/retroroller/issues/177#issue-688535592

**Comment by valadaa48** [comment]
I consider spring to deprecate retrolauncher. It forks the target app and kills itself and leverages the built-in retroarch browser.
