### ISSUE TITLE
RRVL Utilities Playlist Files

### ISSUE THREAD

**Issue by DrBuns3n** [valadaa48/retroroller#180]
Attached are the files necessary to create a Utilities Playlist in RRVL with an entry for the update RRVL script. This avoids the user from having to use the load content dialogue and navigate to the update.sh file.
[retroarch.zip](https://github.com/valadaa48/retroroller/files/5169601/retroarch.zip)

**Comment by valadaa48** [comment]
Thanks for this Firebird. I can't think of how to integrate this properly yet as I prefer not modifying files under the user's homedir.
