### ISSUE TITLE
RRVL: flycast not working

### ISSUE THREAD

**Issue by mariovirgili** [valadaa48/retroroller#181]
Find out why RRVL was not working for me.

Straight out of the box, after downloading the cores needed, it failed to open libretro core for dreamcast and naomi, with the following error:

[INFO] [CORE]: Loading dynamic libretro core from: "/home/odroid/.config/retroarch/cores/flycast_libretro.so"
[ERROR] Failed to open libretro core: "/home/odroid/.config/retroarch/cores/flycast_libretro.so"
Error(s): libGLESv2.so: cannot open shared object file: No such file or directory

**Comment by valadaa48** [comment]
This is fixed in latest update.
