### ISSUE TITLE
RRVL new ppsspp-odroidgo2 not recognizing F1 and F6

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#185]
Previous ppsspp-go2 used F1 to exit and F6 to go to menu. In new ppsspp-odroidgo2 neither key is recognized at all, even when using a USB keyboard and ESC key to enter menu and manually map them.

**Comment by valadaa48** [comment]
Can someone check if this works in other images?

**Comment by valadaa48** [comment]
Try the new ppsspp update, this should work well now. I think F2 (guide) opens the menu.

**Comment by valadaa48** [comment]
@npaladin2000 can we close this?

**Comment by npaladin2000** [comment]
Yep, we're good now.
