### ISSUE TITLE
Potentially add Pico8 compatible libretro core?

### ISSUE THREAD

**Issue by klundry** [valadaa48/retroroller#194]
https://github.com/Jakz/retro8 

I have compiled this as a libretro core and it is working and the games I've tried so far seem to be running pretty well. The audio is not working correctly however. It just plays a loud buzzing sound. Will update if I figure anything out with the audio but perhaps someone more knowledgeable than me can take a look and we can get this new core added?

**Comment by valadaa48** [comment]
Just added
