### ISSUE TITLE
Sleep mode issue

### ISSUE THREAD

**Issue by dj5927** [valadaa48/retroroller#200]
There is a problem with the power saving mode after the update on February 2nd.
The first power saving mode enters normally, but
After waking up, it does not enter the power saving mode again.
Run the game or
Or, after some time has passed, the power saving mode becomes possible again.
Of course, this is also possible only once.

I use OGS.

**Comment by valadaa48** [comment]
Do an update and reboot and it should be working now.

**Comment by dj5927** [comment]
> Do an update and reboot and it should be working now.

It was resolved after the update.
Thank you.
