### ISSUE TITLE
pcsx-rearmed cores fast-forward Freezing issue

### ISSUE THREAD

**Issue by dj5927** [valadaa48/retroroller#208]
The system crashes when using fast forward when running pcsx-rearmed cores.

Moonlight installation
It seems to have occurred after the update around February 14-15.

This is Discord 송재환

**Comment by valadaa48** [comment]
I cannot reproduce this. Can you try from ssh `retroarch32 -L /usr/arm/opt/libretro/pcsx_rearmed_libretro.so <rom>`

**Comment by dj5927** [comment]
The cause was found and resolved.
When G-Sync is turned on in the dos game, it is played in a very smooth screen and used as G-Sync on, but in the pcsx-rearmed core, the G-Sync function is problematic.
When I turned off G-Sync, the problem disappeared.
