### ISSUE TITLE
OGA1.0 can not CPU Overclock

### ISSUE THREAD

**Issue by lancherliu** [valadaa48/retroroller#209]
My device is OGA1.0，I Edit /boot/rrvl.conf and uncomment the cpufreq=151200，then In SSH the CPU stats CPU Freq is 100800.
And i I Edit /boot/rrvl.conf and uncomment the cpufreq=124800，then In SSH the CPU stats CPU Freq is 124800.
Anything what i do,it can not overlock to 151200.
![UPGVO AEAEEUEP9KRC}72JL](https://user-images.githubusercontent.com/77196551/108599305-56fe6500-73cb-11eb-9376-e7facdabd712.png)
![4RUO06_BBR3FI1K~4 P(BSY](https://user-images.githubusercontent.com/77196551/108599311-5e257300-73cb-11eb-8096-2ed2fd1716fd.png)

**Comment by valadaa48** [comment]
I pushed a new kernel update out that should fix this. I would suggest you boot without hte OC and run it manually using setfreq to make sure your unit can handle it

**Comment by lancherliu** [comment]
yep,it is 151200,thank you @valadaa48 
![ETKS2JH2S0Q(QM1PH({2_TM](https://user-images.githubusercontent.com/77196551/108702362-1c6c0800-7544-11eb-95aa-b8894024e667.png)
