### ISSUE TITLE
flycast 64bit issues

### ISSUE THREAD

**Issue by valadaa48** [valadaa48/retroroller#23]
flycast 64bit through ES coredumps on load for some reason, potentially due to memory?

It works through RetroLauncher -> RetroArch though and via ssh command line.

Also, read the wiki on flycast to understand other issues with the 64bit build. Namely, you need to disable auto save/load state as a per-core option.

**Comment by valadaa48** [comment]
https://github.com/libretro/flycast/issues/891

**Comment by npaladin2000** [comment]
We're moving to 32 bit Flycast
