### ISSUE TITLE
F1 + X Resets the game in Retroarch

### ISSUE THREAD

**Issue by tlayne** [valadaa48/retroroller#25]
Not sure if this is by design, but this key combo isn't listed. It will reset the game without warning. I motion to have this removed, or to add a safety to it similar to how F1+F6 requires pressing twice to exit.

**Comment by valadaa48** [comment]
This is fixed in the config in the testing repo. If someone can confirm the package (and config) works then I'll move to the stable repo.

**Comment by tlayne** [comment]
F1 + X is still reset on testing repo and on stable.

**Comment by valadaa48** [comment]
did you try resetting your retroarch.cfg?

**Comment by valadaa48** [comment]
this is now fixed
