### ISSUE TITLE
ES theme customization workaround?

### ISSUE THREAD

**Issue by valadaa48** [valadaa48/retroroller#26]
From the ES theme wiki, I think there might be an easier way to customize a theme:

Copy the theme from /etc/emulationstation/themes to ~/.emulationstation/themes

Rename the new theme directory and change the theme name so it doesn't conflict with the original theme. If someone can test this workflow and update the wiki I think this might actually be a bit easier while allowing you to go back to the original theme and not having to uninstall it.

**Comment by tlayne** [comment]
Yes this works and doesn't require root. I will update the wiki.

**Comment by tlayne** [comment]
Wiki was updated if you want to close this one.
