### ISSUE TITLE
Batocera-es: A and B hardcoded

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#28]
Whatever button is mapped to B is currently "select" and whatever is mapped to "A" is "cancel". Need to switch it.

**Comment by valadaa48** [comment]
is this an issue with emuelec? if not, then I think we should close this if we're going to proceed with EE

**Comment by npaladin2000** [comment]
I agree, and it's not an issue with EmuELEC. One more reason to go that way :)
