### ISSUE TITLE
Permit Root Login is not enabled

### ISSUE THREAD

**Issue by NOirBRight** [valadaa48/retroroller#33]
I can not login as root user by ssh or sftp even using the root account.

by adding "PermitRootLogin yes" in /etc/ssh/sshd_config fixed that.

**Comment by npaladin2000** [comment]
I'm not sure we want to allow that. Most Linux installs don't allow root SSH logins, only sudo su.

**Comment by valadaa48** [comment]
I agree and think we should keep it disabled. It will be too tempting for users to mess up their system. But for anyone that cares, you documented how to enable it.
