### ISSUE TITLE
Time sync is not enabled which cause the pacman update issue

### ISSUE THREAD

**Issue by NOirBRight** [valadaa48/retroroller#34]
> odroid@goadvance:~$ sudo pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
error: failed retrieving file 'retroroller.db' from valadaa48.github.io : SSL certificate problem: certificate is not yet valid
error: failed to update retroroller (download library error)
error: failed retrieving file 'retroroller-testing.db' from valadaa48.github.io : SSL certificate problem: certificate is not yet valid
error: failed to update retroroller-testing (download library error)
error: failed to synchronize all databases

When I using pacman the update the database, these error message appeared.

And the time is not synced.

> odroid@goadvance:~$ date
Sat Apr 25 00:15:08 UTC 2020

After manually set the correct time, pacman works properly.

**Comment by valadaa48** [comment]
This is fixed in the final image
