### ISSUE TITLE
Retroarch32 restart loads Retroarch64 instead

### ISSUE THREAD

**Issue by DrBuns3n** [valadaa48/retroroller#41]
If I load retroarch 32bit from retrolauncher, then restart it, Retroarch 64bit then loads up instead. Then when I quit back to retrolauncher, it's unresponsive and I have to restart it from SSH.

**Comment by valadaa48** [comment]
RetroArch32 when restarted will run 'retroarch' which is the 64bit version. It would involve patching the retroarch source code to get around this. This issue also affects other images that use 64bit/32bit.
