### ISSUE TITLE
emuelec-emulationstation doesn't restart through menu

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#42]
##Selecting restart EmulationStation in menu doesn't work. Hangs at black screen.

**Comment by shoesio** [comment]
Doesn't hang strictly speaking - just closes and leaves a black screen. Launches fine with ssh command

**Comment by valadaa48** [comment]
Please update and re-test when ES if your autoboot.

Restart should work if you launch ES through bootup (systemd). Actually quit will also restart it if it's your autobooter.

**Comment by shoesio** [comment]
Not behaving as described in previous post for me. 
When I select "restart Emulationstation" from the Emuelec Emulationstation quit menu, it still just exits to a black screen, even with Emulationstation set as autolaunch (I used retro launcher to update this)

**Comment by shoesio** [comment]
Selecting "Quit Emulationstation" from emuelec emulation station menu also just closes emulation station, resulting in a black screen

**Comment by adventureFAN** [comment]
Reboot/Shutdown works
Can confirm: Restart EmulationStation (for refresh games) dosn't

**Comment by npaladin2000** [comment]
Yeah, restart still not working

**Comment by M00DY-DEV** [comment]
I can reproduce this.
The only way I can get out is if I ssh: restart

**Comment by valadaa48** [comment]
OK this should now be fixed after update + reboot. Please test again.
