### ISSUE TITLE
emuelec-emulationstation spash screen

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#43]
Splash screen seems to be hard-coded, need to update with RetroRoller art.

**Comment by valadaa48** [comment]
can you find the file that needs change and PR?

**Comment by npaladin2000** [comment]
I tried changing the files, it seems to have no effect.

**Comment by valadaa48** [comment]
does strace help?

**Comment by npaladin2000** [comment]
I'll try that when I get a minute

**Comment by npaladin2000** [comment]
There's no reference to any svg files when I run the trace. 

odroid@goadvance:emulationstation$ strace emulationstation
execve("/usr/bin/emulationstation", ["emulationstation"], 0x7fc85a4460 /* 20 vars */) = 0
brk(NULL)                               = 0x5578647000
faccessat(AT_FDCWD, "/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87486, ...}) = 0
mmap(NULL, 87486, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f9322b000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\350>\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1795200, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9326d000
mmap(NULL, 1493624, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f930be000
mprotect(0x7f93212000, 65536, PROT_NONE) = 0
mmap(0x7f93222000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x154000) = 0x7f93222000
mmap(0x7f93228000, 10872, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f93228000
close(3)                                = 0
mprotect(0x7f93222000, 12288, PROT_READ) = 0
mprotect(0x555dd0a000, 4096, PROT_READ) = 0
mprotect(0x7f93271000, 4096, PROT_READ) = 0
munmap(0x7f9322b000, 87486)             = 0
brk(NULL)                               = 0x5578647000
brk(0x5578668000)                       = 0x5578668000
execve("/usr/local/sbin/bash", ["bash", "/usr/bin/emulationstation"], 0x7fe0168f38 /* 20 vars */) = -1 ENOENT (No such file or directory)
execve("/usr/local/bin/bash", ["bash", "/usr/bin/emulationstation"], 0x7fe0168f38 /* 20 vars */) = -1 ENOENT (No such file or directory)
execve("/usr/bin/bash", ["bash", "/usr/bin/emulationstation"], 0x7fe0168f38 /* 20 vars */) = 0
brk(NULL)                               = 0x5595df7000
faccessat(AT_FDCWD, "/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=87486, ...}) = 0
mmap(NULL, 87486, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8ef69000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libreadline.so.8", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\20Z\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=359232, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8efab000
mmap(NULL, 428352, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8ef00000
mprotect(0x7f8ef50000, 61440, PROT_NONE) = 0
mmap(0x7f8ef5f000, 36864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4f000) = 0x7f8ef5f000
mmap(0x7f8ef68000, 2368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8ef68000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\340\20\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=14288, ...}) = 0
mmap(NULL, 77920, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8eeec000
mprotect(0x7f8eeef000, 61440, PROT_NONE) = 0
mmap(0x7f8eefe000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f8eefe000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\350>\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1795200, ...}) = 0
mmap(NULL, 1493624, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8ed7f000
mprotect(0x7f8eed3000, 65536, PROT_NONE) = 0
mmap(0x7f8eee3000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x154000) = 0x7f8eee3000
mmap(0x7f8eee9000, 10872, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8eee9000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/libncursesw.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\200b\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=470136, ...}) = 0
mmap(NULL, 535640, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8ecfc000
mprotect(0x7f8ed69000, 65536, PROT_NONE) = 0
mmap(0x7f8ed79000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6d000) = 0x7f8ed79000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8efa9000
mprotect(0x7f8eee3000, 12288, PROT_READ) = 0
mprotect(0x7f8ed79000, 20480, PROT_READ) = 0
mprotect(0x7f8eefe000, 4096, PROT_READ) = 0
mprotect(0x7f8ef5f000, 12288, PROT_READ) = 0
mprotect(0x5589ee6000, 20480, PROT_READ) = 0
mprotect(0x7f8efaf000, 4096, PROT_READ) = 0
munmap(0x7f8ef69000, 87486)             = 0
openat(AT_FDCWD, "/dev/tty", O_RDWR|O_NONBLOCK) = 3
close(3)                                = 0
brk(NULL)                               = 0x5595df7000
brk(0x5595e18000)                       = 0x5595e18000
getuid()                                = 1000
getgid()                                = 1000
geteuid()                               = 1000
getegid()                               = 1000
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
ioctl(-1, TIOCGPGRP, 0x7ff04d1a14)      = -1 EBADF (Bad file descriptor)
sysinfo({uptime=16740, loads=[4928, 65600, 109408], totalram=935944192, freeram=379645952, sharedram=1425408, bufferram=32358400, totalswap=0, freeswap=0, procs=135, totalhigh=0, freehigh=0, mem_unit=1}) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTART}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTART}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTART}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
uname({sysname="Linux", nodename="goadvance", ...}) = 0
newfstatat(AT_FDCWD, "/opt/emulationstation", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/opt", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/opt/emulationstation", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/opt", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
getpid()                                = 12528
getppid()                               = 12525
newfstatat(AT_FDCWD, ".", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/local/sbin/bash", 0x7ff04d1648, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/local/bin/bash", 0x7ff04d1648, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/bin/bash", {st_mode=S_IFREG|0755, st_size=1046152, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/bin/bash", {st_mode=S_IFREG|0755, st_size=1046152, ...}, 0) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
faccessat(AT_FDCWD, "/usr/bin/bash", X_OK) = 0
newfstatat(AT_FDCWD, "/usr/bin/bash", {st_mode=S_IFREG|0755, st_size=1046152, ...}, 0) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
faccessat(AT_FDCWD, "/usr/bin/bash", R_OK) = 0
newfstatat(AT_FDCWD, "/usr/bin/bash", {st_mode=S_IFREG|0755, st_size=1046152, ...}, 0) = 0
newfstatat(AT_FDCWD, "/usr/bin/bash", {st_mode=S_IFREG|0755, st_size=1046152, ...}, 0) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
faccessat(AT_FDCWD, "/usr/bin/bash", X_OK) = 0
newfstatat(AT_FDCWD, "/usr/bin/bash", {st_mode=S_IFREG|0755, st_size=1046152, ...}, 0) = 0
geteuid()                               = 1000
getegid()                               = 1000
getuid()                                = 1000
getgid()                                = 1000
faccessat(AT_FDCWD, "/usr/bin/bash", R_OK) = 0
getpid()                                = 12528
getpgid(0)                              = 12525
ioctl(2, TIOCGPGRP, [12525])            = 0
rt_sigaction(SIGCHLD, {sa_handler=0x5589e3a180, sa_mask=[], sa_flags=SA_RESTART}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTART}, 8) = 0
prlimit64(0, RLIMIT_NPROC, NULL, {rlim_cur=3560, rlim_max=3560}) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
openat(AT_FDCWD, "/usr/bin/emulationstation", O_RDONLY) = 3
newfstatat(AT_FDCWD, "/usr/bin/emulationstation", {st_mode=S_IFREG|0755, st_size=65, ...}, 0) = 0
ioctl(3, TCGETS, 0x7ff04d19b0)          = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "#!/usr/bin/env bash\n\ncd /opt/emu"..., 80) = 65
lseek(3, 0, SEEK_SET)                   = 0
prlimit64(0, RLIMIT_NOFILE, NULL, {rlim_cur=1024, rlim_max=512*1024}) = 0
fcntl(255, F_GETFD)                     = -1 EBADF (Bad file descriptor)
dup3(3, 255, 0)                         = 255
close(3)                                = 0
fcntl(255, F_SETFD, FD_CLOEXEC)         = 0
fcntl(255, F_GETFL)                     = 0x20000 (flags O_RDONLY|O_LARGEFILE)
fstat(255, {st_mode=S_IFREG|0755, st_size=65, ...}) = 0
lseek(255, 0, SEEK_CUR)                 = 0
read(255, "#!/usr/bin/env bash\n\ncd /opt/emu"..., 65) = 65
newfstatat(AT_FDCWD, "/opt", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
newfstatat(AT_FDCWD, "/opt/emulationstation", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
chdir("/opt/emulationstation")          = 0
rt_sigprocmask(SIG_BLOCK, [INT CHLD], [], 8) = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f8efa90e0) = 12529
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x5589e363b8, sa_mask=[], sa_flags=0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
wait4(-1, librga:RGA_GET_VERSION:4.00,4.000000
ctx=0x559b9acd00,ctx->rgaFd=3
Rga built version:version:+2017-09-28 10:12:42
rk-debug mali-ver=rsx-p0-1.2

**Comment by tlayne** [comment]
I had no success either when changing various splash logos in the file system. It appears to be baked in. Have we reached out to Shanti?

**Comment by valadaa48** [comment]
The file is logo.png in the resources directory. Make a PR when we have one.

**Comment by M00DY-DEV** [comment]
Try this. dimensions are 480 x 320.
I tried to keep it as small as possible. If the quality is bad then I can do another one. LMK.

![logo](https://user-images.githubusercontent.com/61675748/83094107-e78f5b00-a06e-11ea-9f71-4044170cf260.png)

**Comment by M00DY-DEV** [comment]
Try this one:

![logo](https://user-images.githubusercontent.com/61675748/83094394-9764c880-a06f-11ea-8732-a6dc59a470a4.png)

**Comment by valadaa48** [comment]
looks great! thanks

**Comment by M00DY-DEV** [comment]
with the car:

![logo](https://user-images.githubusercontent.com/61675748/83095545-9765c800-a071-11ea-9fa2-1d3d3546bd09.png)

**Comment by shoesio** [comment]
Looking Fly :)
