### ISSUE TITLE
emuelec-emulationstation Wifi menu

### ISSUE THREAD

**Issue by adventureFAN** [valadaa48/retroroller#51]
Wifi menu dosn't work. It finds no SSIDs.
The status is "not connected" but the IP adress is shown.

Perhaps a conflict with the network.sh?

**Comment by valadaa48** [comment]
This is a known issue but currently wifi on/off works.

**Comment by valadaa48** [comment]
check next update

**Comment by shoesio** [comment]
WIFI now finds SSIDs fine, and I managed to connect using onscreen keyboard. Only slight issues is default menu toggle shows as WIFI off, even though it was actually connected.

**Comment by adventureFAN** [comment]
Yeah can confirm that
