### ISSUE TITLE
emuelec-emulationstation Updates & Downloads menu

### ISSUE THREAD

**Issue by adventureFAN** [valadaa48/retroroller#52]
It is planed to use the Update function? Or the Theme and Bezel download?
Because they have no function right now ^^

**Comment by npaladin2000** [comment]
I'd say we stick with pacman, and EmuELEC's updating is so different we may as well just disable those options and make them go away. :)

**Comment by adventureFAN** [comment]
So updating will be only possible with SSH and pacman commands? =/

**Comment by npaladin2000** [comment]
No, there's a command in RetroLauncher to update also, and I want to put a
command in EmulationStation as well, though it might be under RetroArch
rather than in the menu.

Bryan Pizzuti
npaladin2000@gmail.com

**Comment by adventureFAN** [comment]
Okey this should be fine =)
