### ISSUE TITLE
emuelec-emulationstation "Last played" dosn't work

### ISSUE THREAD

**Issue by adventureFAN** [valadaa48/retroroller#53]
You can activate this entry in "Game Collection Settings" menu.
All other Automaic Collections are working. "Last played" are not.

**Comment by npaladin2000** [comment]
Last played is working for me, can you double-check please?

**Comment by adventureFAN** [comment]
double-checked: still dosn't work for me =/
My games are all ziped or pbp.

**Comment by adventureFAN** [comment]
I found the problem: It must have something to do with the "es-theme-emuelec-carbon". I change to another theme and back and now it works.
