### ISSUE TITLE
Hotkeys needs updating in the wiki

### ISSUE THREAD

**Issue by valadaa48** [valadaa48/retroroller#56]
With the v11 release, some of the default bindings are no longer there.

https://github.com/valadaa48/retroroller/wiki/Hotkeys

**Comment by tlayne** [comment]
Will Global Hotkeys still be available? Or do we need guides for setting global and retroarch hot keys?

**Comment by valadaa48** [comment]
global hotkeys are the same, this refers to RA hotkeys

**Comment by tlayne** [comment]
Bezza updated the graphic this morning. You can close.
