### ISSUE TITLE
Autosave / load causing issues on Flycast RetroRun launched 64bit version (testing channel)

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#58]
Autosave and load seems to be active on the this version of Flycast. Works ok on some games not on others. Jet Grind Radio seems ok with it. Unreal Tournament just loads to black screen with audio playing. Initial launch of Unreal worked ok with video

**Comment by shoesio** [comment]
As you can't enter the Flycast menus on this version no way to fix it for the end user

**Comment by npaladin2000** [comment]
RetroRun is launching the 64 bit version (it complains about the 32 bit version, errors out). I'll look into disabling autosave, but that's a serious functionality limit. Which EmulationStation are you using?

**Comment by shoesio** [comment]
Just the preinstalled test one currently

**Comment by npaladin2000** [comment]
Ok...I switched to the emuelec-testing one, let me see if I can repoduce the issue on that one.

**Comment by npaladin2000** [comment]
I haven't been able to reproduce this yet, can you switch to emuelec-emulationstation and try it through there?

**Comment by shoesio** [comment]
Same thing happens. Where abouts are save states saved for Flycast? They are not in the roms/dreamcast folder... If I can find the save state will delete and try again

**Comment by npaladin2000** [comment]
They should actually be in the home directory

Bryan Pizzuti
npaladin2000@gmail.com

**Comment by valadaa48** [comment]
This is a dup of #23 
Can someone help out the flycast dev and test?

**Comment by npaladin2000** [comment]
We're moving to 32 bit flycast_xtreme
