### ISSUE TITLE
Repeating input on Emulation Station

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#62]
Every now and again the horizontal systems menu goes crazy and starts scrolling on it's own

**Comment by valadaa48** [comment]
I can't reproduce this

**Comment by npaladin2000** [comment]
Nor am i

**Comment by M00DY-DEV** [comment]
Haven't seen this on mine either.

**Comment by tlayne** [comment]
I've had this exact issue.

**Comment by valadaa48** [comment]
@shoesio is it still happening? If so, can you ssh in and run `evtest` and choose the joypad and see if you're getting spammed without touching controls? Maybe your joystick calibration is off. Please report back.

**Comment by shoesio** [comment]
Can't reproduce myself now.  I Ran EVtest and the sticks seems to behave themselves pretty well. I notice now that analogue stick doesn't control menus. Is that a change?  I'd be tempted to close this one out if @tlayne can confirm not effecting hi either now.

**Comment by tlayne** [comment]
I switched to EE ES and it’s not an issue there. Feel free to close.
