### ISSUE TITLE
emuelec-es Settings/StartAtBoot

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#67]
Menu currently shows EmulationStation and RetroArch as options, and probably neither work. This is redundant versus the EmulationStation/RetroLauncher chooser in retrolauncer and can probably be removed unless we want to adapt it to the RR/ES function.

**Comment by valadaa48** [comment]
I fixed this so you can now enable ES or RL at boot

**Comment by adventureFAN** [comment]
Can't select this option becaus the "Emuelec Settings" are disabled?
I can go in the menu anymore.

**Comment by valadaa48** [comment]
this is fixed, please try again

**Comment by npaladin2000** [comment]
I can get at the menu but it doesn't seem to be having an effect, setting for RetroLauncher and rebooting sends me back into ES again.

**Comment by valadaa48** [comment]
this works, you need to select it then hit back or B to exit the menu then it takes effect. This is a ES thing.
