### ISSUE TITLE
Retrolauncher starts in ssh window rather than on device

### ISSUE THREAD

**Issue by shoesio** [valadaa48/retroroller#69]
If you launch retro launcher via ssh session it starts in client window. Not sure if this is desirable behaviour or not tbh :)

**Comment by npaladin2000** [comment]
Probably not a bad thing for people new to SSH, but there's no way to exit
it and no buttons along the bottom.

**Comment by valadaa48** [comment]
This is by design. You need to use `sudo systemctl start retrolauncher`. Also, 'q' quits using a keyboard.
