### ISSUE TITLE
Unable to launch RetroLauncer2 from EmulationStation

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#71]
If one is booting to EmulationStation, only way to launch it is to switch over via SSH currently.

**Comment by valadaa48** [comment]
yeah I need to look into this, do you know if it works from the vanilla ES?

**Comment by npaladin2000** [comment]
No, wasn't working there either

Bryan Pizzuti
npaladin2000@gmail.com

**Comment by valadaa48** [comment]
this is fixed in the new release
