### ISSUE TITLE
RA performance mode from RL

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#73]
When launching and then exiting RetroArch from RetroLauncher and then exiting, system remains in max performance mode rather than switching to normal/interactive.

**Comment by valadaa48** [comment]
I wasn't aware retroarch via retrolauncher sets performance mode. can you check the retrolauncher.toml file to verify?

**Comment by npaladin2000** [comment]
It's just the bare command:

[[apps]]
name = "RetroArch"
cmd = "retroarch"
[[apps]]
name = "RetroArch 32-bit"
cmd = "retroarch32"
[[apps]]
name = ""
[[apps]]
name = "Emulation Station"
cmd = "emulationstation"
[[apps]]
name = "PPSSPP"
cmd = "performance on; ppsspp; performance off"

Bryan Pizzuti
npaladin2000@gmail.com

**Comment by valadaa48** [comment]
so this is expected, there's nothing to change perf mode so it will stay the same
