### ISSUE TITLE
emuelec-emulationstation Entries that have no Function

### ISSUE THREAD

**Issue by adventureFAN** [valadaa48/retroroller#79]
Disclaimer: Just a cosmetic suggestion. This is VERY minor.

Here are the menu entries that have (in my eyes) no function:

EmuELEC Settings
 - Video Mode
 - Always show boot video (?)

Games Settings 
 - The whole menu (very sadly)

Sound Settings
- Frontend Music (?)

Updates & Downloads
 - The whole menu

System Settingy
- Power Save Mode (?)
- Video Output
- Audio Output
- Overclock
- "Storage" Section (no entry)
- Developer
  - Use RetroArch RGUI Menu
  - Redetect Games Lang/Region
  - unsure about some other entries

**Comment by valadaa48** [comment]
should we remove them?

**Comment by npaladin2000** [comment]
I won't use them.

**Comment by adventureFAN** [comment]
Also Game Settings? *cry*

**Comment by valadaa48** [comment]
we can leave that in as a reminder that it has to be fixed. But I can change the label to (not working) ro something

**Comment by valadaa48** [comment]
OK I removed most of these. Also sound controls are working now.
