### ISSUE TITLE
RetroArch - Dosbox_core_libretro not working

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#82]
I can start the same EXE files in dosbox_libretro. Anyone else experiencing this issue?

**Comment by valadaa48** [comment]
Error(s): /usr/share/libretro/dosbox_core_libretro.so: undefined symbol: SDL_mutexP

**Comment by npaladin2000** [comment]
Guess we stlick with dosbox_libretro? Probably not a lot of demand for it anyway.
