### ISSUE TITLE
emuelec-emulationstation Cannot Open Retrolauncher

### ISSUE THREAD

**Issue by M00DY-DEV** [valadaa48/retroroller#83]
Launching Retrolauncher from within EE ES goes straight to the `goadvance login:` prompt.

**Comment by valadaa48** [comment]
did you update the latest packages and reboot?

**Comment by M00DY-DEV** [comment]
I did at about 2am last night.
I'll do another update and see if it works.

**Comment by valadaa48** [comment]
closing this because it's reported to be working for others. reopen if it's still an issue
