### ISSUE TITLE
General Dreamcast performance

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#85]
This issue is to cover discussion/documentation/fixing of the issues running Dreamcast and related (NAOMI/AtomisWave) games on RetroRoller

**Comment by shoesio** [comment]
![6166B5E3-E3EC-490E-9A01-CA255D0A0A90](https://user-images.githubusercontent.com/65093305/83354151-2400d680-a34f-11ea-9c02-ab6594e19eaa.png)

**Comment by shoesio** [comment]
Currently emulation station launches 64bit flycast libretto core using retrorun. Not the fastest option, but sadly Flycast 32bit will not launch correctly from Emulation Station.

**Comment by npaladin2000** [comment]
We need to get the 32 bit RetroRun working so we can test that.

**Comment by npaladin2000** [comment]
FYI the flycast_xtreme_libretro.so core works great when run maually within RetroArch.

**Comment by npaladin2000** [comment]
We will need libevdev.so.2 present to run retroarch32, @valadaa48 please compile and push out when you have a chance

**Comment by npaladin2000** [comment]
Ok got my hands on the missing library and tried it. Got the following when tracing it out:

ioctl(12, DRM_IOCTL_GET_CAP, 0xffec24e0) = 0
ioctl(12, DRM_IOCTL_SET_VERSION, 0xffec2494) = -1 EACCES (Permission denied)
write(1, "eglGetPlatformDisplayEXT failed.", 32eglGetPlatformDisplayEXT failed.) = 32
write(1, "\n", 1
)                       = 1
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x38} ---
gettimeofday({tv_sec=1069478512518481, tv_usec=2330128220286306643}, NULL) = 0
write(1, "[err] 00:01:249 libretro/common."..., 112[err] 00:01:249 libretro/common.cpp:373 E[COMMON]: SIGSEGV @ f71f2632 ... 0x38 -> was not in vram (dyna code 0)
) = 112
write(1, "[inf] Fatal error : segfault\n in"..., 84[inf] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 374

) = 84
gettimeofday({tv_sec=1075830769149265, tv_usec=4995127810847819076}, NULL) = 0
write(1, "[err] 00:01:250 libretro/libretr"..., 66[err] 00:01:250 libretro/libretro.cpp:3084 E[COMMON]: DEBUGBREAK!
) = 66
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0xf1f58068} ---
gettimeofday({tv_sec=1079069174490449, tv_usec=2330128220286306643}, NULL) = 0
write(1, "[err] 00:01:251 libretro/common."..., 118[err] 00:01:251 libretro/common.cpp:373 E[COMMON]: SIGSEGV @ f1f58068 ... 0xf1f58068 -> was not in vram (dyna code 0)
) = 118
write(1, "[inf] Fatal error : segfault\n in"..., 84[inf] Fatal error : segfault
 in signal_handler -> core/libretro/common.cpp : 374

) = 84
gettimeofday({tv_sec=1083759278777681, tv_usec=4995127810847819076}, NULL) = 0
write(1, "[err] 00:01:252 libretro/libretr"..., 66[err] 00:01:252 libretro/libretro.cpp:3084 E[COMMON]: DEBUGBREAK!
) = 66
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0xf1f58068} ---
+++ killed by SIGILL (core dumped) +++
Illegal instruction (core dumped)

**Comment by npaladin2000** [comment]
The big difference here is I think retrorun64 was compiled for RetroRoller. I grabbed the retrorun32 binary from stock. We may need it recompiled for our platform.

**Comment by npaladin2000** [comment]
We are now testing dreamcast performance using flycast_xtreme_libretro and retrorun32. Seems to be improved.

**Comment by npaladin2000** [comment]
We've settled on using retrorun32 and Flycast_xtreme_libretro
