### ISSUE TITLE
Odroid WiFi Module 5 not working in RR - need support for either RTL8811AU or RTL8812AU/CU chipsets in RR-testing.

### ISSUE THREAD

**Issue by BadBrent** [valadaa48/retroroller#86]
I'm still trying to get my EDUP RTL8811AU chipset WiFi dongle to work in RetroRoller-testing and thus far my device doesn't even see the dongle when connected to the OGA v1.1.  I know that @valadaa48 has had success with his dongle but I haven't been able to make touchdown yet with mine.  The Odroid WiFi Module 5 has been discontinued and has been replaced with the RTL8812AU chipset and so I believe that I ordered this module and should have it in hand within 48 hours.  Some sources say it could be the RTL8812CU chipset instead,, but I'm hoping that it's actually the AU model.  I also ordered a duplicate EDUP module with the original RTL8811AU chipset integrated into it, so I'm hoping that there's an easy way to get it working (or if the RTL8812CU dongle works I'd be happy with that as well).  Lets see if we can get either of these two 802.11ac 433mbps dongles working in RR.

**Comment by npaladin2000** [comment]
See the post regarding disabling 5 GHz WiFI.
