### ISSUE TITLE
USB 3.0 unpowered devices can brick your micro SD card

### ISSUE THREAD

**Issue by BadBrent** [valadaa48/retroroller#88]
Just finished some testing, and as it turns out a few high-powered USB 3.0 devices can cause your micro SD card to get bricked to the point you have to re-image your micro SD card.  I was able to replicate this using a 256GB HP USB 3.1 flash drive an once I plugged it in and tried to mount it the system became unresponsive and corrupted the FAT32 partition.  Be careful with the new version 1.1 devices and high-powered USB 3.0/3.1 devices when you're doing any file transfers or connecting 802.11ac dongles.

Odroid officially dropped support for the WiFi Module 5 but do support the 5A dongle, but ras of right now it is unsupported by Retro Roller according to CrashOverride.  The new 5A dongle is actually a higher-powered dongle based on the RTL8812AU chipset which is a 2x2 adapter while the Module 5 is only RTL8811AU and is 1x1 which draws less power but can still brick your card if you connect to a 5ghz access point.  A lot of this info is known already but Crash made the official statement that some USB 3.0/3.1 devices can be in fact detrimental to your micro SD card's performance as well as having the possibility of corrupting the front FAT32 partition used to boot Retro Roller.  If you want to copy large files as I am trying to do, connect your OGA v1.1 to a powered USB adapter so that you do not brick your SD card completely.

**Comment by npaladin2000** [comment]
This has been mitigated by restricting the device to 2.4 GHz only, blocking access to the more power hungry 5 GHz band.
