### ISSUE TITLE
dr4stic installer needs to download configs

### ISSUE THREAD

**Issue by valadaa48** [valadaa48/retroroller#91]
the configs are not bundled anymore due to v10 v11 differences

**Comment by npaladin2000** [comment]
Ok I need to know what to look for so the script can tell the difference, then once we have the v11 config I can just point it to the Github repo depending on which is detected.

**Comment by valadaa48** [comment]
I pasted the check before, can you try to search for it?

**Comment by npaladin2000** [comment]
Drastic installed updated to detect platform and download appropriate configs
