### ISSUE TITLE
Minimal theme not accepting input

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#95]
When attempting to scrape metadata, none of the input dialgs show any text or allow any to be entered. Possibly the text is white on a white background? not sure.

**Comment by npaladin2000** [comment]
@tlayne

**Comment by npaladin2000** [comment]
Confirmed, if I keep track of what I type, it DOES actually type, it's just invisible.

**Comment by tlayne** [comment]
Fixed. Needs to be packaged to commit: https://github.com/tlayne/es-theme-minimal/commit/932df79963f6ee288f78a2808c60a8334d8e6837

@valadaa48 @npaladin2000

**Comment by valadaa48** [comment]
I pushed the update

**Comment by npaladin2000** [comment]
Fixed with different font color choices.
