### ISSUE TITLE
es_systems.cfg needs platform set

### ISSUE THREAD

**Issue by NeonLightning** [valadaa48/retroroller#96]
for these systems a platform needs set to scrape
saturn, famicom, super famicom, intellevision, master system

**Comment by npaladin2000** [comment]
Seems to already be set up, please make sure your es_systems.cfg matches this file: https://raw.githubusercontent.com/valadaa48/retroroller/master/configs/OGA_V1/es_systems.cfg

**Comment by npaladin2000** [comment]
@NeonLightning any of them still not working after updating?

**Comment by npaladin2000** [comment]
Verified working
