### ISSUE TITLE
Minimal theme - no video issue

### ISSUE THREAD

**Issue by npaladin2000** [valadaa48/retroroller#97]
If a game has no video, it just shows a black background. Any way to get this to fail over to a screenshot instead, if one is availabe? @tlayne

**Comment by tlayne** [comment]
Can you change line 270 something in your v4.xml to this and let me know if things look good?

`<showSnapshotNoVideo>true</showSnapshotNoVideo>`

**Comment by npaladin2000** [comment]
Yeah, that's a ton better. If you want to update the theme with that I'll close this out.

**Comment by tlayne** [comment]
Yes I’ll fix it up.

**Comment by npaladin2000** [comment]
Ok I'll close this. One less issue.
